name = "Project Crowbar"
author = "Unofficial fork by Jammersmurph"
version = "auto"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a02fd3b069910a1a7da0b5b7e78f3c8336dbd40c8afc232b2b11fedceadee00"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
