name = "Project Crowbar"
author = "Unofficial fork by Jammersmurph"
version = "auto"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bff8e47b859fc1318d5a1c6c45648daee77fe4393370184621e4f69a0589d26"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
