name = "Project Crowbar"
author = "Unofficial fork by Jammersmurph"
version = "auto"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a20b0f6205bc7e5e61ee478907deba31e62d11c80b442cca73222d835f9f92e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
