plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.eclipsesource.minimal-json:minimal-json:0.9.5'
    implementation 'commons-cli:commons-cli:1.4'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

application {
    mainClass = 'link.infra.packwiz.installer.bootstrap.Main'
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes('Main-Class': application.mainClass.get())
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
